model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  # vllm-0 hermes
  - model_name: NousResearch/Hermes-3-Llama-3.1-8B
    litellm_params:
      model: openai/NousResearch/Hermes-3-Llama-3.1-8B
      api_base: http://vllm-0:8000/v1
      api_key: none
  # vllm-1 qwen
  - model_name: Qwen/Qwen2.5-7B-Instruct
    litellm_params:
      model: openai/Qwen/Qwen2.5-7B-Instruct
      api_base: http://vllm-1:8000/v1
      api_key: none
  # vllm-2 llama
  - model_name: meta-llama/Llama-3.1-8B-Instruct
    litellm_params:
      model: openai/meta-llama/Llama-3.1-8B-Instruct
      api_base: http://vllm-2:8000/v1
      api_key: none
  # vllm-3 tool ace
  - model_name: Team-ACE/ToolACE-8B
    litellm_params:
      model: openai/Team-ACE/ToolACE-8B
      api_base: http://vllm-3:8000/v1
      api_key: none
  # vllm-4 granite
  - model_name: ibm-granite/granite-3.1-8b-instruct
    litellm_params:
      model: openai/ibm-granite/granite-3.1-8b-instruct
      api_base: http://vllm-4:8000/v1
      api_key: none
  # vllm-5-hermes
  - model_name: internlm/internlm2_5-7b-chat
    litellm_params:
      model: openai/internlm/internlm2_5-7b-chat
      api_base: http://vllm-5:8000/v1
      api_key: none
  # vllm-6 functionary
  - model_name: meetkai/functionary-small-v3.1
    litellm_params:
      model: openai/meetkai/functionary-small-v3.1
      api_base: http://vllm-6:8000/v1
      api_key: none
  # text-embeddings-inference jina embed w/ OAI-compatible endpoint
  - model_name: jinaai/jina-embeddings-v2-base-en
    litellm_params:
      model: openai/jinaai/jina-embeddings-v2-base-en
      api_base: http://text-embeddings-inference/v1
      api_key: none

general_settings:
  master_key: 'sk-blacklight-key'
