include:
  - docker-compose.yml

services:

  # vllm service(s)
  vllm-0:
    image: vllm/vllm-openai:latest
    entrypoint: [
      "vllm", "serve", "NousResearch/Hermes-3-Llama-3.1-8B",
      "--enable-prefix-caching", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "131072",
      "--enable-auto-tool-choice", "--tool-call-parser", "hermes"
    ]
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HUGGINGFACE_TOKEN:?error}
    volumes:
      - type: bind
        source: ${HF_HOME:?error}
        target: /root/.cache/huggingface
      - type: bind
        source: ./node/inference/configs
        target: /usr/app # configs like chat templates, vllm configs, tool parsers
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ "gpu" ]
              count: 1


  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    command: --config /app/config.yaml
    restart: unless-stopped
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY:?error}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY:?error}
      DATABASE_URL: postgresql://${LOCAL_DB_POSTGRES_USERNAME?:error}:${LOCAL_DB_POSTGRES_PASSWORD:?error}@pgvector:5432/litellm
    volumes:
      - ./node/inference/litellm/litellm_config.single_gpu.yml:/app/config.yaml # this should be the litellm config file
    ports:
      - '4000:4000'
